version: '3'
services:
  web:
    image: nginx:stable-alpine
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html
      - ./nginx-config/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build:
      context: .
    volumes:
      - ./src:/var/www/html    